(s1.both <- ggplot(ftp_ul_4g_filter, aes(x=RSRP, y=Throughput.UL.MAC, colour="red")) + geom_jitter(size=1.5, na.rm = TRUE) + guides(colour=FALSE))
(s2.both <- ggplot(ftp_dl_4g_filter, aes(x=SNR, y=Throughput.DL.MAC, colour="red")) + geom_jitter(size=1.5, na.rm = TRUE) + guides(colour=FALSE) + scale_y_continuous(limits=c(0, 200000)))
(s2.both <- ggplot(ftp_dl_4g_filter, aes(x=RSRP, y=Throughput.DL.MAC, colour="red")) + geom_jitter(size=1.5, na.rm = TRUE) + guides(colour=FALSE))
(m1.both <- arrangeGrob(s1.both, s2.both, ncol=2, nrow=1))
ggsave(m1.both, file=paste0("./Charts/Scatter_Throughput_Compare.jpeg"), width=20, height=10, dpi=100)
